{% set name = "django-stubs" %}
{% set version = "4.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-stubs-{{ version }}.tar.gz
  sha256: dadab39b46d9ae8f37a8e879c590f39a9e042b565c03fa0c5a8f754b441b1f23

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools <64
  run:
    - django
    - django-stubs-ext >=4.2.2
    - mypy >=1.0.0
    - python >=3.7
    - tomli
    - types-pytz
    - types-pyyaml
    - typing-extensions

test:
  imports:
    - django_stubs_ext
    - mypy_django_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/django-stubs
  summary: Mypy stubs for Django
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
