{% set name = "django-stubs" %}
{% set version = "4.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-stubs-{{ version }}.tar.gz
  sha256: e60b43de662a199db4b15c803c06669e0ac5035614af291cbd3b91591f7dcc94

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - django
    - django-stubs-ext >=4.2.5
    - mypy >=1.0.0
    - python >=3.8
    - tomli
    - types-pytz
    - types-pyyaml
    - typing-extensions

test:
  imports:
    - django_stubs_ext
    - mypy_django_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/django-stubs
  summary: Mypy stubs for Django
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
