{% set name = "django-stubs" %}
{% set version = "5.2.0" %}
{% python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 07e25c2d3cbff5be540227ff37719cc89f215dfaaaa5eb038a75b01bbfbb2722

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - django
    - asgiref
    - django-stubs-ext =={{ version }}
    - tomli
    - typing_extensions >=4.0
    - types-pyyaml

test:
  imports:
    - django_stubs_ext
    - mypy_django_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/typeddjango/django-stubs
  summary: Mypy stubs for Django
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
