schema_version: 1

context:
  name: django-stubs
  version: 5.2.1
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: e58260958e58f7b6a8da6bba56d6b31d16c0414079a4aa6baa01c668bd08d39d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - python >=${{ python_min }}
    - django
    - django-stubs-ext ==${{ version }}
    - tomli
    - typing_extensions >=4.0
    - types-pyyaml

tests:
  - python:
      imports:
        - django_stubs_ext
        - mypy_django_plugin
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Mypy stubs for Django
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/typeddjango/django-stubs

extra:
  recipe-maintainers:
    - thewchan
