schema_version: 1

context:
  name: django-stubs
  version: "6.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: e1ca63634221b57a55e16562b9b6d1849aeee2cabfd0fc026084dbe8aa893366

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.8.22,<0.9.0
  run:
    - python >=${{ python_min }}
    - django
    - django-stubs-ext >=${{ version }}
    - tomli
    - typing_extensions >=4.11.0
    - types-pyyaml

tests:
  - python:
      imports:
        - django_stubs_ext
        - mypy_django_plugin
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Mypy stubs for Django
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/typeddjango/django-stubs

extra:
  recipe-maintainers:
    - thewchan
